/*==============================================================*/
/* Table: DEPARTAMENTO                                          */
/*==============================================================*/
/*CREATE TABLE DEPARTAMENTO (
   ID_DEPTO             VARCHAR(2)            NOT NULL,
   ID_PAIS              VARCHAR(3),
   NOMBRE               VARCHAR(20)           NOT NULL,
   CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (ID_DEPTO)
);*/

INSERT INTO DEPARTAMENTO (ID_DEPTO, ID_PAIS, NOMBRE)VALUES ('DEP', 'PAIS','NOMBRE');

INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Ama', 'COL', 'Amazonas');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Ant', 'COL', 'Antioquia');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Ara', 'COL', 'Arauca');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Atl', 'COL', 'Atlántico');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Bog', 'COL', 'Bogotá');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Bol', 'COL', 'Bolívar');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Boy', 'COL', 'Boyacá');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Cal', 'COL', 'Caldas');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Caq', 'COL', 'Caquetá');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Cas', 'COL', 'Casanare');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Cau', 'COL', 'Cauca');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Ces', 'COL', 'Cesar');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Cho', 'COL', 'Chocó');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Cór', 'COL', 'Córdoba');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Cun', 'COL', 'Cundinamarca');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Gua', 'COL', 'Guainía');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Guv', 'COL', 'Guaviare');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Hui', 'COL', 'Huila');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('LaG', 'COL', 'La Guajira');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Mag', 'COL', 'Magdalena');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Met', 'COL', 'Meta');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Nar', 'COL', 'Nariño');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Nsa', 'COL', 'Norte de Santander');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Put', 'COL', 'Putumayo');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Qui', 'COL', 'Quindío');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Ris', 'COL', 'Risaralda');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Sap', 'COL', 'San Andrés y Providencia');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('San', 'COL', 'Santander');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Suc', 'COL', 'Sucre');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Tol', 'COL', 'Tolima');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Vac', 'COL', 'Valle del Cauca');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Vau', 'COL', 'Vaupés');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('Vic', 'COL', 'Vichada');

