/*==============================================================*/
/* Table: DEPARTAMENTO                                          */
/*==============================================================*/
/*CREATE TABLE DEPARTAMENTO (
   ID_DEPTO             VARCHAR(2)            NOT NULL,
   ID_PAIS              VARCHAR(3),
   NOMBRE               VARCHAR(20)           NOT NULL,
   CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (ID_DEPTO)
);*/

INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('91', 'COL', 'Amazonas');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('5', 'COL', 'Antioquia');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('81', 'COL', 'Arauca');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('8', 'COL', 'Atlántico');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('11', 'COL', 'Bogotá');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('13', 'COL', 'Bolívar');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('15', 'COL', 'Boyacá');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('17', 'COL', 'Caldas');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('18', 'COL', 'Caquetá');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('85', 'COL', 'Casanare');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('19', 'COL', 'Cauca');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('20', 'COL', 'Cesar');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('27', 'COL', 'Chocó');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('23', 'COL', 'Córdoba');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('25', 'COL', 'Cundinamarca');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('94', 'COL', 'Guainía');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('95', 'COL', 'Guaviare');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('41', 'COL', 'Huila');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('44', 'COL', 'La Guajira');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('47', 'COL', 'Magdalena');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('50', 'COL', 'Meta');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('52', 'COL', 'Nariño');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('54', 'COL', 'Norte de Santander');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('86', 'COL', 'Putumayo');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('63', 'COL', 'Quindío');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('66', 'COL', 'Risaralda');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('88', 'COL', 'San Andrés y Providencia');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('68', 'COL', 'Santander');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('70', 'COL', 'Sucre');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('73', 'COL', 'Tolima');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('76', 'COL', 'Valle del Cauca');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('97', 'COL', 'Vaupés');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, ID_PAISE, NOMBRE)VALUES ('99', 'COL', 'Vichada');

