/*==============================================================*/
/* Table: CIUDAD                                                */
/*==============================================================*/
/*CREATE TABLE CIUDAD (
   ID_CIUDAD            VARCHAR(5)            NOT NULL,
   ID_DEPTO             VARCHAR(2)            NOT NULL,
   NOMBRE               VARCHAR(20)           NOT NULL,
   CONSTRAINT PK_CIUDAD PRIMARY KEY (ID_CIUDAD)
);*/

INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Let', 'Amazonas', 'Leticia');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Med', 'Antioquia', 'Medellín');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Ara', 'Arauca', 'Arauca');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Bar', 'Atlántico', 'Barranquilla');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Bog', 'Bogotá', 'Bogotá');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Cart', 'Bolívar', 'Cartagena de Indias');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Tun', 'Boyacá', 'Tunja');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Man', 'Caldas', 'Manizales');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Flo', 'Caquetá', 'Florencia');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Yop', 'Casanare', 'Yopal');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Pop', 'Cauca', 'Popayán');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Vap', 'Cesar', 'Valledupar');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Qd', 'Chocó', 'Quibdó');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Mon', 'Córdoba', 'Montería');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Bog', 'Cundinamarca', 'Bogotá');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Iní', 'Guainía', 'Inírida');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('SJG', 'Guaviare', 'San José del Guaviare');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Nei', 'Huila', 'Neiva');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Rio', 'La Guajira', 'Riohacha');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Sam', 'Magdalena', 'Santa Marta');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Viv', 'Meta', 'Villavicencio');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Pas', 'Nariño', 'Pasto');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('San José de Cúcuta', 'Norte de Santander', 'San José de Cúcuta');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Moc', 'Putumayo', 'Mocoa');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Arm', 'Quindío', 'Armenia');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Per', 'Risaralda', 'Pereira');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Sad', 'San Andrés y Providencia', 'San Andrés');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Buc', 'Santander', 'Bucaramanga');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Sinc', 'Sucre', 'Sincelejo');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Iba', 'Tolima', 'Ibagué');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Cal', 'Valle del Cauca', 'Cali');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Mit', 'Vaupés', 'Mitú');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('Ptc', 'Vichada', 'Puerto Carreño');


