/*==============================================================*/
/* Table: CIUDAD                                                */
/*==============================================================*/
/*CREATE TABLE CIUDAD (
   ID_CIUDAD            VARCHAR(5)            NOT NULL,
   ID_DEPTO             VARCHAR(2)            NOT NULL,
   NOMBRE               VARCHAR(20)           NOT NULL,
   CONSTRAINT PK_CIUDAD PRIMARY KEY (ID_CIUDAD)
);*/


INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('91001', 'Amazonas', 'Leticia');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('5001', 'Antioquia', 'Medellín');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('81001', 'Arauca', 'Arauca');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('8001', 'Atlántico', 'Barranquilla');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('11001', 'Bogotá', 'Bogotá');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('13001', 'Bolívar', 'Cartagena de Indias');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('15001', 'Boyacá', 'Tunja');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('17001', 'Caldas', 'Manizales');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('18001', 'Caquetá', 'Florencia');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('85001', 'Casanare', 'Yopal');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('19001', 'Cauca', 'Popayán');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('20001', 'Cesar', 'Valledupar');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('27001', 'Chocó', 'Quibdó');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('23001', 'Córdoba', 'Montería');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('25001', 'Cundinamarca', 'Agua de dios');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('94001', 'Guainía', 'Inírida');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('95001', 'Guaviare', 'San José del Guaviare');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('41001', 'Huila', 'Neiva');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('44001', 'La Guajira', 'Riohacha');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('47001', 'Magdalena', 'Santa Marta');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('50001', 'Meta', 'Villavicencio');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('52001', 'Nariño', 'Pasto');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('54001', 'Norte de Santander', ' Cúcuta');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('86001', 'Putumayo', 'Mocoa');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('63001', 'Quindío', 'Armenia');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('66001', 'Risaralda', 'Pereira');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('88001', 'San Andrés y Providencia', 'San Andrés');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('68001', 'Santander', 'Bucaramanga');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('70001', 'Sucre', 'Sincelejo');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('73001', 'Tolima', 'Ibagué');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('76001', 'Valle del Cauca', 'Cali');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('97001', 'Vaupés', 'Mitú');
INSERT INTO DEPARTAMENTO (ID_CIUDAD, ID_DPTO, NOMBRE)VALUES ('99001', 'Vichada', 'Puerto Carreño');
